eco_da_mata_project/eco_da_mata_project/urls.py
from rest_framework.routers import DefaultRouter
from rest_framework import permissions
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from community_app.views import CommunityViewSet, NewsViewSet 
from people_app.views import PeopleViewSet
from project_app.views import ProjectViewSet
from events_app.views import EventViewSet

Router = DefaultRouter()
Router.register('community', CommunityViewSet)
Router.register('new', NewsViewSet)
Router.register('people', PeopleViewSet)
Router.register('project', ProjectViewSet)
Router.register('events', EventViewSet)


schema_view = get_schema_view(
    openapi.Info(
        title="Eco da Mata",
        default_version='v1',
        description='Sem descrição',
        terms_of_service="https://www.community.com/terms/",
        contact=openapi.Contact(name='Equipe virtual - Eco da Mata'),
        license=openapi.License(name="Sem nome"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

#É uma boa prática nomear os paths de vocês. Principalmente quando tiverem trabalhando com formulários.
urlpatterns = [
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schena-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schena-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schena-redoc'),
    path('api/', include(Router.urls)),
    path('community/', include('community_app.urls')), 
    path('project/', include('project_app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eco_da_mata_project/events_app/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path("create/", views.create_event, name = "create_event"),
    path("list/", views.get_events, name = "get_events"),
    path("<uuid:event_id>", views.get_single_event , name = "get_single_event"),
    path('edit/<uuid:event_id>/', views.edit_event, name='edit_event'),
    path('delete/<uuid:event_id>/', views.delete_event, name='delete_event'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eco_da_mata_project/events_app/models.py
from django.db import models
from project_app.models import Project
import uuid

#Events an reviews entities:

class Event(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, auto_created=True, editable=False)
    title = models.CharField(max_length=50, verbose_name="Título")
    body = models.CharField(max_length=300, verbose_name="Descrição")
    #__

    begin_date = models.DateField(verbose_name="Data de início")
    end_date = models.DateField(verbose_name="Data de fim")
    time = models.TimeField(verbose_name="Horário")
    address = models.CharField(max_length=100, verbose_name="Endereço")
    location = models.CharField(max_length=100, verbose_name="Localização")
    #__

    link = models.URLField(verbose_name="Link")
    value = models.DecimalField(decimal_places=2,max_digits=10, verbose_name="Valor")
    pix_key = models.URLField(max_length=100, verbose_name="Chave PIX") 
    pix_key_owner = models.CharField(max_length=100, verbose_name="Dono da chave PIX")
    bank_name = models.CharField(max_length=100, verbose_name="Banco")
    #__

    pdf_link = models.URLField(max_length=100, null=True, verbose_name="Link para PDF")
    questionary_link = models.URLField(max_length=100, null=True, verbose_name="Link para questionário")
    #--
    category = models.CharField(max_length=20,default="Vazio" ,choices =[
    ("F", "Feira"),
    ("Ft", "Festividade"),
    ("Cl", "Celebração")    
    ])
    format = models.CharField(max_length=20, default="Vazio" ,choices =[
    ("P", "Presencial"),
    ("V", "Virtual"),
    ("H", "Híbrido")
    ])
    #__
    
    fk_project = models.ForeignKey(Project,on_delete=models.CASCADE, verbose_name="Associado ao projeto", null=True)

    def __str__(self):
        return self.title

class review(models.Model):
    title = models.CharField(max_length=50,verbose_name="Título")
    body = models.CharField(max_length=300, verbose_name="Mensagem")
    author = models.CharField(max_length=100)
    grade = models.CharField(max_length=20 ,choices=[
    ("R", "Ruim"),
    ("B", "Bom"),
    ("Mb", "Muito bom")
    ], verbose_name="Avaliação")
    fk_event = models.ForeignKey(Event, on_delete=models.CASCADE, null= True)

    def __str__(self):
        return self.title

eco_da_mata_project/events_app/forms.py
from django import forms
from .models import Event, review

class event_form(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ["title","body","begin_date","end_date","time","address","location",
                  "link", "value", "pix_key", "pix_key_owner", "bank_name", "pdf_link", "questionary_link",
                  "category", "format"]
        widgets = {
            'begin_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            'time' : forms.TimeInput(format='%H:%M', attrs={'type' : 'time'})
        }

class deleteeventform(forms.ModelForm):
    delete = forms.IntegerField(label="Deletar Evento:")
    

eco_da_mata_project/events_app/views.py
from django.shortcuts import render,redirect,get_object_or_404, HttpResponse
from .models import Event
from .forms import event_form, deleteeventform
from rest_framework import viewsets
from .serializers import EventSerializer


class EventViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

# Create your views here.

def create_event(request):
    if request.method == "POST":
        form = event_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            print('FORMULÁRIO SALVO')
        else:
            print('FORMULÁRIO NAO SALVO')
        return redirect ('get_events')
    else:
        form = event_form()
        context = {"form": form}
        return render(request,"event_form.html",context)


def get_events(request):
    events = Event.objects.all()
    context = {"events": events}
    return render(request,"event_list.html",context)


def get_single_event(request, event_id): 
    event = get_object_or_404(Event, pk = event_id)
    return render(request, "single_event.html", {"event":event})


def edit_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    if request.method == 'POST':
        form = event_form(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            return redirect('../../list/', event_id=event.id)
    else:
        form = event_form(instance=event)
    return render(request, 'edit_event.html', {'form': form, 'event': event})


def delete_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    if request.method == 'POST':
        event.delete()
        return redirect('get_events')
    return render(request, 'delete_event_form.html', {'event': event})

eco_da_mata_project/events_app/templates/delete_event_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Excluir evento</title>
</head>
<body>
    <h2>Tem certeza que quer excluir o evento "{{ event.title }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sim</button>
    </form>
</body>
</html>

eco_da_mata_project/events_app/templates/edit_event.html
<!DOCTYPE html>
<html>
<head>
    <title>Editar Evento</title>
</head>
<body>
    <h1>Editar evento: {{ event.title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" style="background-color: #00e41e; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Enviar</button>
    </form>
    <form action="{% url 'get_single_event' event.id %}" method="get" style="display:inline;">
        <button type="submit" style="background-color: #f44336; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Cancelar</button>
    </form>
</body>
</html>

eco_da_mata_project/events_app/templates/event_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Evento - Criação</title>
    
</head>
<body>
    <h1>Evento - Criação</h1>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" style="background-color: #00e41e; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Enviar</button>
    </form>
</body>
</html>

eco_da_mata_project/events_app/templates/event_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Eventos</title>
</head>
<body>
    <h1>Eventos</h1>
    <form action="{% url 'create_event' %}" method="get" style="display:inline;">
        <button type="submit" style="background-color: #00e41e; border: none; color: rgb(0, 0, 0); padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">+ Criar novo evento</button>
    </form>
    <ul>
        {% for event in events %}
            <li>
                <h2>
                    <a href="{% url 'get_single_event' event.id %}">{{ event.title }}</a>
                </h2>
                {% if event.profile_image %}
                    <img src="{{ event.profile_image.url }}" width="300" height="150">
                {% endif %}
            </li>
        {% empty %}
            <li>Nenhum evento encontrado.</li>
        {% endfor %}
    </ul>
</body>
</html>

eco_da_mata_project/events_app/templates/eventform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <title>Evento - Criação</title>
    
</head>
<body>
    <h1>Evento - Criação</h1>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
</body>
</html>

eco_da_mata_project/events_app/templates/single_event.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ event.title }}</title>
</head>
<body>
    <h1>{{ event.title }}</h1>
    <p><strong>Descrição:</strong> {{ event.body }}</p>
    <p><strong>Data de Início:</strong> {{ event.begin_date }} | <strong>Data de Término:</strong> {{ event.end_date }}</p>
    <p><strong>Endereço:</strong> {{ event.address }} | <strong>Local:</strong> {{ event.location }}</p>
    <p><strong>Horário:</strong> {{ event.time }}</p>
    <p><strong>Valor: </strong>R${{ event.value }}</p>
    <p><strong>Chave Pix:</strong> {{ event.pix_key }}</p>
    <p><strong>Proprietário da Chave Pix:</strong> {{ event.pix_key_owner }}</p>
    <p><strong>Nome do Banco:</strong> {{ event.bank_name }}</p>
    <p><strong>Link do PDF:</strong> <a href="{{ event.pdf_link }}">{{ event.pdf_link }}</a></p>
    <p><strong>Link do Questionário:</strong> <a href="{{ event.questionary_link }}">{{ event.questionary_link }}</a></p>
    <p><strong>Link:</strong> <a href="{{ event.link }}">{{ event.link }}</a></p>
    <p><strong>Categoria:</strong> {{ event.get_category_display }}</p>
    <p><strong>Formato:</strong> {{ event.get_format_display }}</p>
    <p><strong>Projeto:</strong> {{ event.fk_project }}</p>
    

</form>

    <form action="{% url 'get_events' %}" method="get" style="display:inline;">
        <button type="submit" style="background-color: #494949; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Voltar para a lista</button>
    </form>
    <form action="{% url 'edit_event' event.id %}" method="get" style="display:inline;">
        <button type="submit" style="background-color: #2024ff; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Editar</button>
    </form>
    <form action="{% url 'delete_event' event.id %}" method="post" style="display:inline;">
        {% csrf_token %}
        <button type="submit" style="background-color: #ff0000; border: none; color: white; padding: 10px 24px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; margin: 4px 2px; cursor: pointer; border-radius: 10px;">Excluir</button>
    </form>
</body> 
</html>

eco_da_mata_project/events_app/templates/singleevent.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ event.title }}</title>
</head>
<body>
    <h1>{{ event.title }}</h1>
    <p><strong>Body:</strong> {{ event.body }}</p>
    {% if event.profile_image %}
        <p><strong>Profile Image:</strong><br>
        <img src="{{ event.profile_image.url }}" alt="{{ event.title }}"></p>
    {% endif %}
    <p><strong>Start Date:</strong> {{ event.start_date }}</p>
    <p><strong>End Date:</strong> {{ event.end_date }}</p>
    <p><strong>Time:</strong> {{ event.time }}</p>
    <p><strong>Address:</strong> {{ event.address }}</p>
    <p><strong>Location:</strong> {{ event.location }}</p>
    <p><strong>Link:</strong> <a href="{{ event.link }}">{{ event.link }}</a></p>
    <p><strong>Value:</strong> {{ event.value }}</p>
    <p><strong>Pix Key:</strong> {{ event.pix_key }}</p>
    <p><strong>Pix Key Owner:</strong> {{ event.pix_key_owner }}</p>
    <p><strong>Bank Name:</strong> {{ event.bank_name }}</p>
    <p><strong>PDF Link:</strong> <a href="{{ event.pdf_link }}">{{ event.pdf_link }}</a></p>
    <p><strong>Questionary Link:</strong> <a href="{{ event.questionary_link }}">{{ event.questionary_link }}</a></p>
    <p><strong>Category:</strong> {{ event.get_category_display }}</p>
    <p><strong>Format:</strong> {{ event.get_format_display }}</p>
</body>
</html>